### PR TITLE
Add tests for /stations router

### PR DESCRIPTION
**Pull request by lizyn**

### CODE REVIEW

**Comment by lizyn** [comment]
@AdvisorChuanChuan I guess the test failed because CI doesn't have the most updated .env file. Could you try updating it on the settings page?

**Comment by AdvisorChuanChuan** [comment]
> 

I have updated /server/.env secret in our repo early today as well as our shared google drive to have the api key for Open Route Service (path planning). What else do I need to add?

**Comment by lizyn** [comment]
Copied from the CI log:
```
FAIL tests/routes/stations.test.js
  ● Test suite failed to run

    Failed to parse private key: Error: Only 8, 16, 24, or 32 bits supported: 528

      21 |
      22 | admin.initializeApp({
    > 23 |   credential: admin.credential.cert(serviceAccount),
         |                                ^
      24 | });
      25 |
      26 | module.exports = admin;

      at new ServiceAccount (node_modules/firebase-admin/lib/app/credential-internal.js:144:1[9](https://github.com/AdvisorChuanChuan/CIS550-JuiceFinder/pull/15/checks#step:7:10))
      at new ServiceAccountCredential (node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
      at Object.cert (node_modules/firebase-admin/lib/app/credential-factory.js:[10](https://github.com/AdvisorChuanChuan/CIS550-JuiceFinder/pull/15/checks#step:7:11)3:54)
      at Object.cert (services/firebaseAdmin.js:23:32)
      at Object.require (middlewares/checkAuth.js:1:15)
      at Object.require (routes/users.js:5:23)
      at Object.require (routes/index.js:9:22)
      at Object.require (server.js:14:9)
      at Object.require (tests/routes/stations.test.js:4:[13](https://github.com/AdvisorChuanChuan/CIS550-JuiceFinder/pull/15/checks#step:7:14))
```

@YichengShen Do you have any idea of what might cause this error?

**Comment by YichengShen** [comment]
Looks like it only supports keys with 8, 16, 24, or 32 bits, but it got 528 bits. The API keys for Firebase admin SDK are long strings. 

Prior to the update of the new secret, we did not have this issue. Is this correct?

In the secret, maybe we could try moving the line of the new API key to be above the section of Firebase admin keys.

**Comment by lizyn** [comment]
I agree that the problem could be from the private key not being correctly parsed. I am troubleshooting following the instruction here https://github.com/gladly-team/next-firebase-auth/discussions/95#discussioncomment-2891225 

So I made some minor changes to `firebaseAdmin.js` and pushed it. In addition, I removed the quote around the value of `FIREBASE_ADMIN_PRIVATE_KEY` in `.env`. I tested locally and things still work.

@AdvisorChuanChuan, can you update github repo secrets as well by removing the quote around the value of `FIREBASE_ADMIN_PRIVATE_KEY` and see how it goes?

**Comment by lizyn** [comment]
> Prior to the update of the new secret, we did not have this issue. Is this correct?

I am not sure if it's due to the secret update, as there are other variables: for example, we introduced new tests in this PR and we never had backend tests before this.

**Comment by AdvisorChuanChuan** [comment]
> [](https://github.com/gladly-team/next-firebase-auth/discussions/95#discussioncomment-2891225)

Done. Both the secret and the google drive file have `FIREBASE_ADMIN_PRIVATE_KEY` without any quotes `"`.

**Pull request merged**
